../bin/run_raptorx-ss3.pl ../examples/3eoj.seq
../bin/run_raptorx-ss3.pl ../examples/2yhx.seq
../bin/run_raptorx-ss3.pl ../examples/2sil.seq
../bin/run_raptorx-ss3.pl ../examples/2cth.seq
../bin/run_raptorx-ss3.pl ../examples/1s01.seq
../bin/run_raptorx-ss3.pl ../examples/1lba.seq
../bin/run_raptorx-ss3.pl ../examples/1gcm.seq
../bin/run_raptorx-ss3.pl ../examples/1dts.seq
../bin/run_raptorx-ss3.pl ../examples/1dar.seq
../bin/run_raptorx-ss3.pl ../examples/1cbh.seq
../bin/run_raptorx-ss3.pl ../examples/1aaz.seq
touch timestmpHERE
../bin/run_raptorx-ss8.pl ../examples/3eoj.seq
../bin/run_raptorx-ss8.pl ../examples/2yhx.seq
../bin/run_raptorx-ss8.pl ../examples/2sil.seq
../bin/run_raptorx-ss8.pl ../examples/2cth.seq
../bin/run_raptorx-ss8.pl ../examples/1s01.seq
../bin/run_raptorx-ss8.pl ../examples/1lba.seq
../bin/run_raptorx-ss8.pl ../examples/1gcm.seq
../bin/run_raptorx-ss8.pl ../examples/1dts.seq
../bin/run_raptorx-ss8.pl ../examples/1dar.seq
../bin/run_raptorx-ss8.pl ../examples/1cbh.seq
../bin/run_raptorx-ss8.pl ../examples/1aaz.seq
